apiVersion: v1
kind: Service
metadata:
  name: santander-iib
  labels:
    app: @docker.container.name@
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: @service.port@
    targetPort: @service.port@
  selector:
    app: @docker.container.name@
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: santander-iib 
  labels:
    app: @docker.container.name@
spec:
  template:
    metadata:
      labels:
        app: @docker.container.name@
    spec:
      containers:
      - name: santander-iib
        image: @docker.qualified.image@
        imagePullPolicy: @docker.image.pull.policy@
        ports:
        - containerPort: @service.port@
          name: iib
 
